services:
  # Anvil - Local Ethereum blockchain (with deployed contracts)
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: luxdao-anvil
    entrypoint: ["anvil"]
    command: ["--host", "0.0.0.0", "--chain-id", "1337", "--accounts", "10", "--block-time", "3"]
    ports:
      - "8545:8545"
    networks:
      - luxdao
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 5s
      timeout: 3s
      retries: 5

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: luxdao-postgres
    environment:
      POSTGRES_USER: luxdao
      POSTGRES_PASSWORD: luxdao123
      POSTGRES_DB: luxdao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - luxdao
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luxdao"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: luxdao-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - luxdao
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # IPFS Node
  ipfs:
    image: ipfs/kubo:latest
    container_name: luxdao-ipfs
    environment:
      IPFS_PROFILE: server
    ports:
      - "5001:5001" # API
      - "8080:8080" # Gateway
      - "4001:4001" # P2P
    volumes:
      - ipfs_data:/data/ipfs
    networks:
      - luxdao
    healthcheck:
      test: ["CMD-SHELL", "ipfs id"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  luxdao:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  ipfs_data: